### ISSUE TITLE
Allow empty lines?

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/PEFF#3]
The current spec disallows empty lines between entries. Is that too harsh? It's pretty easy for parsers to ignore them. 

Reviewer wrote:
That is more strict than FASTA, where newlines are ignored until the next header token “>”. Is that really necessary? Of course, existing FASTA parsers will probably crash however, because of the description block

Shall we recant and allow empty lines? Parsers are required to ignore them?

What do you think?

**Comment by pabinz** [comment]
In the original spec, we were not accurately aware that FASTA did allow these empty lines. As this is indeed allowed (not specifically forbidden in the BLAST documentation for instance), we could align PEFF and recommend not to add empty lines: 
"There SHOULD NOT be any empty lines between individual sequence entries."

(SHOULD instead of MUST)

**Comment by edeutsch** [comment]
Is everyone in agreement with that? Explicitly allow it, but discourage it?

**Comment by edeutsch** [comment]
The specification has been amended to discourage but permit empty lines anywhere in the document. Some example files provide examples of empty lines. The validator issues a warning, but not an error.
